name:                markovbot
version:             0.1.0.0
github:              "fwcd/MarkovBot"
license:             BSD3
author:              "fwcd"
maintainer:          "fwcdmail@gmail.com"
copyright:           "2018 fwcd"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/fwcd/MarkovBot#readme>

dependencies:
- base >= 4.10.1.0
- discord-haskell >= 0.6.0
- pipes >= 4.3.9
- containers >= 0.5.10.2
- random >= 1.1
- text >= 1.2.3.0
- bytestring >= 0.10.8.2

library:
  source-dirs: src/lib

executables:
  markovbot-exe:
    main:                Main.hs
    source-dirs:         src/app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - markovbot

tests:
  markovbot-test:
    main:                Spec.hs
    source-dirs:         src/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - markovbot
