name:                markovbot
version:             0.1.0.0
github:              "fwcd/MarkovBot"
license:             BSD3
author:              "fwcd"
maintainer:          "fwcdmail@gmail.com"
copyright:           "2018 fwcd"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/fwcd/MarkovBot#readme>

dependencies:
- base >= 4.10.1.0
- discord-haskell == 1.1.2
- cache == 0.1.1.2
- pipes >= 4.3.9
- containers >= 0.5.10.2
- random >= 1.1
- text >= 1.2.3.0
- bytestring >= 0.10.8.2
- Rasterific >= 0.7.4.1
- JuicyPixels == 3.3.3.1
- FontyFruity >= 0.5.3.4
- temporary >= 1.3

library:
  source-dirs: src

executables:
  markovbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - markovbot

tests:
  markovbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - markovbot
