name:                markovbot
version:             0.1.0.0
github:              "fwcd/MarkovBot"
license:             BSD3
author:              "fwcd"
maintainer:          "fwcdmail@gmail.com"
copyright:           "2018 fwcd"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/fwcd/MarkovBot#readme>

dependencies:
- base
- discord-haskell
- pipes
- text

library:
  source-dirs: src/lib

executables:
  markovbot-exe:
    main:                Main.hs
    source-dirs:         src/app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - markovbot

tests:
  markovbot-test:
    main:                Spec.hs
    source-dirs:         src/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - markovbot
