name:                markovbot
version:             0.1.0.0
github:              "fwcd/MarkovBot"
license:             BSD3
author:              "fwcd"
maintainer:          "fwcdmail@gmail.com"
copyright:           "2018 fwcd"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fwcd/MarkovBot#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src/lib

executables:
  markovbot-exe:
    main:                Main.hs
    source-dirs:         src/app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - markovbot

tests:
  markovbot-test:
    main:                Spec.hs
    source-dirs:         src/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - markovbot
