resolver: lts-11.2

packages:
- .

extra-deps:
- discord-haskell-0.6.0
- discord-gateway-0.2.2
- discord-rest-0.2.2
- discord-types-0.2.2
- url-2.1.3
- aeson-1.2.4.0
- req-1.0.0
- websockets-0.12.5.2
- http-client-0.5.13.1
- wuss-1.1.11
